# -*- coding: utf-8 -*-
"""Copia de PC_1_Quimica_UNMSM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NRQyPeQElGZj4UGW6UIVjUX5omCKsANU

$$\Large \textit{UNMSM | Química}$$
$$\large \textbf{PC Nº1 | Materia y clasificación}$$

_Profesor: Jesus Alvarado Huayhuaz_

Todas las indicaciones para la presentación de la práctica son explicadas en clase y brindadas en el material de enunciado de preguntas en formato PDF.

## Pregunta 1: Sobre el ABC de python (4 puntos)

Durante la semana de revisión del material "ABC de python", reflexiona sobre qué conceptos aprendiste con claridad y cuáles consideras los más desafiantes. A continuación resuelve los siguiente ejercicios, puedes ayudarte del material en http://bit.ly/3YKICSZ.
"""

# Imprime la versión de python que usas y las palabras reservadas de python para esa versión.
!python --version

# Crea una matriz de 3x3 e imprime la suma de los elementos en su diagonal (traza).

matriz = [
    [1, 2, 3],
    [6, 6, 6],
    [7, 8, 9]
]

suma_traza = 0
for i in range(len(matriz)):
    suma_traza += matriz[i][i]

print("Matriz:")
for fila in matriz:
    print(fila)

print(f"Suma de la diagonal (traza): {suma_traza}")

# Guarda como variable la masa atómica de los elementos C, H y O, e imprime la masa molecular del etanol.ç
masa_C = 12.01
masa_H = 1.008
masa_O = 15.999

# Fórmula del etanol: C2H5OH
num_C = 2
num_H = 6
num_O = 1


masa_molecular_etanol = (num_C * masa_C) + (num_H * masa_H) + (num_O * masa_O)

print(f"Masa molecular del etanol (C2H5OH): {masa_molecular_etanol} u")

# Busca la temperatura de fusión en Celsius de 5 metales y guárdalos en una lista. Imprime las temperaturas en Kelvin

temperaturas_fusion_celsius = [1538, 660.32, 1064.18, 1455, 419.53]

def celsius_a_kelvin(celsius):
    return celsius + 273.15

temperaturas_kelvin = [celsius_a_kelvin(temp) for temp in temperaturas_fusion_celsius]


for i in range(len(temperaturas_fusion_celsius)):
    print(f"Temperatura de fusión de metal {i+1}: {temperaturas_kelvin[i]:.2f} K")

"""## Pregunta 2: Operaciones (4 puntos)

Escribe un programa que lea repetidamente elementos químicos en español hasta que el usuario introduzca “fin”. Una vez se haya introducido “fin”, muestra por pantalla (o sea imprime) el total de elementos ingresados. Si el usuario introduce cualquier otra cosa que no sea un elemento químico, detecta su fallo usando try y except, muestra un mensaje de error y pasa al siguiente elemento.
"""

elementos_quimicos = set([
    "hidrogeno", "helio", "litio", "berilio", "boro",  # Ejemplos de elementos
    # ... (lista de elementos químicos en español)
])

total_elementos = 0

while True:
    entrada = input("Introduce un elemento químico en español (o 'fin' para terminar): ").strip().lower()

    if entrada == "fin":
        break

    try:
        if entrada in elementos_quimicos:
            total_elementos += 1
        else:
            print("Error: Elemento químico no reconocido.")
    except KeyboardInterrupt:
        print("\nPrograma interrumpido por el usuario.")
        break

print(f"Total de elementos ingresados: {total_elementos}")

"""# Pregunta 3: Conservación de la masa (4 puntos)

### Código necesario para generar la imagen

### Reacción química

Demuestra cómo se cumple la conservación de la masa en la siguiente reacción química. Sugerencia: hacer un balance estequiométrico y luego emplear la masa molecular de reactivos y productos.
"""

SmilesDrawer(value=[("Rxn", "C(C1C(C(C(C(O1)O)O)O)O)O.O=O>>C(=O)=O.O")], theme='dark', background="#1e1e1e", options={'scale': 1.25})

"""## Pregunta 4: Notación científica (4 puntos)"""



"""Imprime las siguientes operaciones según la notación científica:

(1) $1.321 \times 10^{-4} + 8.5 \times 10^{-2}$

(2) $1.71 \times 10^{3} - 2.01 \times 10^{2}\$

(3) $(7.4 \times 10^5)(7.2 \times 10^4)$

(4) $(7.4 \times 10^5)/(7.2 \times 10^4)$

## Pregunta 5: Método científico (4 puntos)

El enigma del LK-99 parece haber sido resuelto por investigadores a través de un exhaustivo proceso científico. El trabajo ha desenterrado pruebas concluyentes que desmienten su supuesta superconductividad y revelan su verdadera naturaleza. Esta conclusión frustra las esperanzas de que el LK-99, compuesto de cobre, plomo, fósforo y oxígeno, fuera el primer superconductor funcional a temperatura y presión ambiente. En su lugar, los análisis han demostrado que impurezas presentes en el material, especialmente el sulfuro de cobre, son responsables de su resistividad eléctrica y de una levitación parcial en presencia de un imán, características similares a las de los superconductores. La investigación comenzó cuando un equipo coreano afirmó que el LK-99 era un superconductor a temperaturas y presiones inusuales.

Artículo: https://bit.ly/3surZ1W
Leer el siguiente artículo y explica cómo es aplicado el método científico. Emplea como máximo 300 palabras.
"""